### ISSUE TITLE
BUG : QR code download not working on mobile devices

### ISSUE THREAD

**Issue by khardikk** [hady68/https---github.com-hady68-QR-Code-Gen#1]
Steps to Reproduce:

1. Access the website with the QR code generator on a mobile device.
2. Fill in the required information and generate the QR code.
3. Attempt to download the QR code image by clicking on the "Save Image" button.
4. Observe that instead of downloading the image, the entire page is being downloaded.
5. Expected Behavior:
6. When clicking on the "Save Image" button, the QR code image should be downloaded directly on the mobile device without downloading the entire page.

Additional Information:

Tested on multiple mobile devices (specify device models and operating systems if available).
Verified that the issue does not occur on desktop browsers.
The issue persists even after trying the suggested solution of using the fetch API to download the image.

**Comment by Sage-2001** [comment]
Hey, i am working on this assign it to me.

**Comment by khardikk** [comment]
> Hey, i am working on this assign it to me.

Hey let me know a realistic timeline you'll be able to fix this ?

**Comment by Sage-2001** [comment]
> > Hey, i am working on this assign it to me.
> 
> Hey let me know a realistic timeline you'll be able to fix this ?

I think it will take me sometime atleast 1-2 days as I am not able to identify the bug, it's working perfectly fine on Dekstop but not on mobile.

**Comment by khardikk** [comment]
> > > Hey, i am working on this assign it to me.
> > 
> > Hey let me know a realistic timeline you'll be able to fix this ?
> 
> I think it will take me sometime atleast 1-2 days as I am not able to identify the bug, it's working perfectly fine on Dekstop but not on mobile.

Sure that sounds reasonable, I'm assigning this issue to you, please update as you work on it to keep an active communication

**Comment by Sage-2001** [comment]
Hey @hady68 it's done. I have checked it

**Comment by Sage-2001** [comment]
hey @hady68 can you close this issue? It's still open.
